PACKAGE_NAME="lor-i2s"
PACKAGE_VERSION="1.0.0"
BUILT_MODULE_NAME[0]="designware_i2s"
DEST_MODULE_LOCATION[0]="/updates/dkms"
MAKE[0]="make KVER=${kernelver} KDIR=${kernel_source_dir}"
CLEAN="make KVER=${kernelver} KDIR=${kernel_source_dir} clean"
AUTOINSTALL="yes"
